### ISSUE TITLE
Use csv sniffer to guess dialect of csv

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data.js#22] opened 2017-12-16 07:31 UTC
Use this package to guess dialect of csv before loading https://www.npmjs.com/package/csv-sniffer

Test with loading a csv file with semicolon delimiters etc

**Comment by anuveyatsu** [comment] 2018-02-05 09:20
DUPLICATE of https://github.com/datahq/pm/issues/87 and https://github.com/datahq/data-cli/issues/259

**Closed as completed by anuveyatsu** 2018-02-05 09:20 UTC
Labels: duplicate
